### PR TITLE
Options

### LINKED ISSUE #25: getCommentType limits parsing to *only* CSS or HTML
Hi @himedlooff - based on my success making this work with 11ty for css documentation, I decided to try and port my solution to document nunjucks macros:

```js
const doxOptions = {
  regex: {
    njk: {
      opening: /^\{\#*\s*@docs[^\n]*\n/m,
      closing: /\#\}/,
      comment: /^\{\#\s*@docs[^*]*\#+(?:[^/*][^*]*\#+)*\}/gm,
      ignore: /^\{\#\s*@no-docs[\s\S]*/gm
    }
  }
};

fs.readdir(includeDir, (err, files) => {
  if (err) throw err;
  files.filter((file) => file.endsWith('.njk')).forEach((file) => {
    const docs = doxray([filePath], doxOptions);
  }
}
```
This returns an error:

```
Uncaught exception: (more in DEBUG output)
> Cannot read property 'comment' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'comment' of undefined
        at Object.utils.getFileContents (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/utils.js:99:41)
        at Doxray.<anonymous> (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/doxray.js:68:42)
        at Array.forEach (<anonymous>)
        at Doxray.parse (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/doxray.js:64:7)
        at Doxray.run (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/doxray.js:49:17)
        at doxray (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/index.js:10:25)
        at files.filter.forEach (/Users/miriamsuzanne/Sites/oddleventy/content/_data/dox.js:35:20)
        at Array.forEach (<anonymous>)
        at fs.readdir (/Users/miriamsuzanne/Sites/oddleventy/content/_data/dox.js:31:51)
        at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

After some testing, it looks like the problem is in the `getCommentType()` switch, which forces any unknown extension into `css`. In fact, it works if I register my new regex patterns as `css` in the options object, and continue to run it on `.njk` files.

### PR DESCRIPTION
**Pull request by mirisuzanne**
Fixes #25 

Changes:
- `utils.getCommentType()` returns the extension, without attempting to convert related languages
- `Doxray.prototype.parse()` looks for regex based on extension, or falls back to CSS if no extension-based regex is available (same end result for languages with existing support)
- `utils.handleOptions()` will merge new languages into the default regex map, so it's possible to set a new language option without overriding the default options

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -61,9 +61,15 @@ describe('doxray.js, core methods', function() {
       );
     });
 
-    it('should respect custom regex patterns in options', function () {
+    it('should respect custom regex patterns in options while retaining defaults', function () {
```
Comment (himedlooff) [inline test/index.js]: I'm not sure I get how this test is checking to see if the defaults are retained.

To do that I would want to remove the HTML key from this options object and then parse an HTML file to see if it works. If it does then presumably it's using the HTML regex from Doxray.prototype. If it doesn't then it might mean that the regex option is replacing the prototype.

**Comment by himedlooff** [comment]
Thank you! Looks good. Just had a comment about the test.

File: test/index.js (hunk 1 above)
Comment (mirisuzanne) [reply test/index.js]: Yeah, I was moving fast and misread both these tests. Should be better now?

File: test/test.html [hunk 2]
```diff
@@ -0,0 +1,15 @@
+<!DOCTYPE html>
+<html lang="en">
+<head>
+  <meta charset="UTF-8">
+  <meta name="viewport" content="width=device-width, initial-scale=1.0">
+  <meta http-equiv="X-UA-Compatible" content="ie=edge">
+  <title>Document</title>
+</head>
+<body>
+<!-- doxray
```
Comment (mirisuzanne) [inline test/test.html]: The start-of-line `^` limitation in your regex is strange to me. What's the reason for it?

Comment (himedlooff) [reply test/test.html]: To increase my confidence since I'm not very strong in regex. I'm open to better matching patterns if you have ideas.

**Comment by himedlooff** [comment]
Thanks for the update!
I published a new release:
- https://www.npmjs.com/package/doxray/v/0.9.0
- https://github.com/himedlooff/doxray/releases/tag/0.9.0
